apiVersion: v1
kind: Secret
metadata:
  name: donfra-secrets
  namespace: donfra-eng
type: Opaque
stringData:
  # Database
  POSTGRES_USER: donfra
  POSTGRES_PASSWORD: arfnod
  POSTGRES_DB: donfra_study
  DATABASE_URL: postgres://donfra:arfnod@postgres:5432/donfra_study?sslmode=disable

  # API Authentication
  PASSCODE: "7777"
  ADMIN_PASS: "7777"
  JWT_SECRET: don-secret

  # Google OAuth (update these for production)
  GOOGLE_CLIENT_ID: 591319272586-nc3aig9s7i2hf72h0i2on937f1n7qckp.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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

  # DeepSeek AI
  DEEPSEEK_API_KEY: sk-e374a9bbcda34b9fad9c82aaf2771d23

  # LiveKit Keys
  LIVEKIT_API_KEY: devkeydevkeydevkeydevkeydevkeydevkey
  LIVEKIT_API_SECRET: APISECRETdevkeyAPISECRETdevkeyAPISECRETdevkey
