---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: donfra-eng
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: doneowth/donfra-ui:1.0.28
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: ui-config
          env:
            # Pass LiveKit secrets for server-side token generation
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: donfra-secrets
                  key: LIVEKIT_API_KEY
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: donfra-secrets
                  key: LIVEKIT_API_SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10

---
# ClusterIP Service for UI - Gateway handles external traffic
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: donfra-eng
  labels:
    app: ui
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: ui
