---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: donfra-eng
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: doneowth/donfra-runner:1.0.0
          ports:
            - containerPort: 8090
              name: http
          env:
            - name: ADDR
              value: ":8090"
            - name: SANDBOX_MODE
              value: "direct"
            - name: MAX_CONCURRENT
              value: "4"
            - name: DEFAULT_TIMEOUT_MS
              value: "5000"
            - name: MAX_TIMEOUT_MS
              value: "10000"
            - name: MAX_OUTPUT_BYTES
              value: "65536"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8090
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8090
          #   initialDelaySeconds: 5
          #   periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: runner
  namespace: donfra-eng
  labels:
    app: runner
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      name: http
  selector:
    app: runner
